version: '3'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file: .env
    depends_on:
      - redis

  mysql:
    image: mysql:8
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    restart: always

volumes:
  mysql_data:
